executors:
  default:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

version: 2.1
jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  node_dependencies:
    executor: default
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: v1-node-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: v1-node-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

  test_lint:
    executor: default
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-node-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Run eslint
          command: yarn lint --format junit -o test_results/eslint.xml
      - store_test_results:
          path: test_results

  test_jest:
    executor: default
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-node-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Run jest
          command: yarn test --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "test_results/jest.xml"
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - node_dependencies:
          requires:
            - checkout_code
      - test_lint:
          requires:
            - node_dependencies
      - test_jest:
          requires:
            - node_dependencies
